mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
spring:
  profiles:
    active: dev
  application: tiku-task
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /systeminfo